name: 🐛 Bug Report
description: Report a bug or issue with the documentation site
title: "[Bug]: "
labels: ["type: bugfix", "status: needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      options:
        - Documentation content
        - Site navigation
        - Search functionality
        - UI/UX (design/layout)
        - Build/deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "What's happening that shouldn't be happening?"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "What did you expect to see?"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop images here"

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop/Laptop
        - Tablet
        - Mobile Phone

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Any other relevant information?"
